name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
        ACTOR: ${{ github.actor }}
        REPOSITORY-URL: ${{ github.repositoryUrl }}
    steps:
      - run: echo "${ ACTOR }" # githubコンテキストの参照
      - run: echo "${ REPOSITORY-URL }"